### ISSUE TITLE
Mod Configuration

### ISSUE THREAD

**Issue by DennysPelegrin** [RubixDev/EnchantedShulkers#10]
Sorry I don't understand the configuration section for mods that have containers. I'm using a mod called upgraded shulkers and I'd like to place the enchantments on it. Is this only possible if I'm the developer of a mod (since the section in the readme is title "For Mod Developers"? Is there a way to add a container to the enchantedshulkers:portable_container tag without being a developer?

**Comment by RubixDev** [comment]
Well the idea is that the developer of the other mod adds their shulker boxes to my `portable_container` tag and I would recommend you open an issue on their mod to request this, but in the meantime it is also possible to create a data pack on your own. All you need to do for that is create a folder inside your world's datapack folder (on Windows i think it's `%AppData%/.minecraft/saves/<world_name>/datapack/`) named for example 'upgradable_shulkers_enchantedshulkers_compat' and then inside that folder create a file called `pack.mcmeta` with following contents:

```json
{
  "pack": {
    "pack_format": 10,
    "description": "Upgradable Shulkers / EnchantedShulkers compat"
  }
}
```

Then create the nested folders `data/enchantedshulkers/tags/items/` next to the `pack.mcmeta` file and inside the innermost `items` folder create a file called `portable_container.json` with these contents:

```json
{
  "replace": false,
  "values": [
    "#us:iron_shulkers",
    "#us:gold_shulkers",
    "#us:diamond_shulkers",
    "#us:netherite_shulkers"
  ]
}
```

With this data pack loaded you should then be able to use the `Siphon` and `Refill` enchantments on the upgraded shulkers
