### ISSUE TITLE
Server-side only

### ISSUE THREAD

**Issue by ILikeFood971** [RubixDev/EnchantedShulkers#13]
I was wondering if it would be at all possible to make this compatible with vanilla clients on a fabric server? Would there be some way to edit the mod and use a required server resource pack to make it work? I was thinking this might be able to be a setting or something and have some sort of link to allow people to download it using Minecraft's built in resource pack manager. I understand that you can use this on server side only, I have tried it, it just is impossible to tell what shulkers are enchanted and to see any enchanted books added by the mod. It would make it a lot easier for some of the members on our server if this was possible.

**Comment by RubixDev** [comment]
Sadly I don't think it's possible to have vanilla clients know about the enchantments. As you said, the main mechanic already works with vanilla clients, but adding enchantments is way more complex then simply using a resource pack.

I am not that very knowledgeable about resource packs though, but i can actually imagine it to somehow be possible to create one that can change the look or tooltip of shulkers based on the nbt tag they have.

**Comment by ILikeFood971** [comment]
That's kind of what I was thinking. If there was some way to have a resource pack change the look of a shulker/book if it had a certain nbt tag. I know that there are other mods/plugins out there that add some enchantments and are only required server-side. I do not understand much about resource packs or mods so I probably couldn't create anything like that though. I'll do some more research and see what I can come up with. Thanks for the help!

**Comment by ILikeFood971** [comment]
Just found a useful reddit post that might work. 

https://www.reddit.com/r/fabricmc/comments/o76rbu/comment/h2x9gxd/

Correct me if I'm wrong, but couldn't you be able to just detect whether the client has the mod installed, and if they don't just send them different information that just includes the enchantment name in the extended name of the item? I know it wouldn't be perfect because of the glint on the shulkers, but this would still allow somebody who isn't able to add this mod to their client to be able to tell if it is enchanted. I really don't understand how mods are coded, but could anybody give me a few instructions about how to do this myself?

**Comment by RubixDev** [comment]
Well I don't have much experience with sending packets from and to the client myself either, but that sounds like a reasonable and surely possible way to improve server side only support. I'm a big fan of server-side only mods too, so I will definitely give that a try when I find time. Thanks for the research!

**Comment by RubixDev** [comment]
Ok so I worked on this a lot today and got so far that the enchantments are shown in the tooltip on vanilla clients, but now non-vanilla clients show the enchantment names twice and my attempts to fix that so far have all been unsuccessful.

**Comment by RubixDev** [comment]
nvm, turns out I just didn't realise it already worked :facepalm:
v1.1.0 will have this implemented so that vanilla clients can see the enchantments in item tooltips at least.
