### ISSUE TITLE
Request: "Missing" Enchantment "mass storage"

### ISSUE THREAD

**Issue by Monroe1701** [RubixDev/EnchantedShulkers#14]
In Xisumavoids video where another idea about stack sizes. While I don't think the stack sizes should be upped to 999 in general, but an enchantment for shulker boxes to enlarge the stack size in storage/personal storage by x times (e.g.15x64=960~999) whould be nize. With the refill enchantement there is no need to enlarge the stack sitze for the user.
Don't know if this would be possible, but a nice addition anyway
.

**Comment by RubixDev** [comment]
I am not really a fan of increasing stack sizes and as Xisuma mentions in the video, it's probably a lot of coding effort, especially when restricting it to certain containers. Additionally, this would conflict with the work done in #13, trying to keep the mod's core functionality server-side only.

**Comment by Monroe1701** [comment]
Yes, I feel the same, I'm not a fan of greater stack sizes either, but Xisumavoid had a point here, especially for builders of big structures.
Thats why I restricted it to only shulker boxes with a specific enchantment to complement the two enchantments of this mod.

But even without this enchantment is this mod a great addition to my personal modpack and I will put it to good use. Thanks
