### ISSUE TITLE
Improve Enchanted Ender Chest Capabilities

### ISSUE THREAD

**Issue by ILikeFood971** [RubixDev/EnchantedShulkers#17]
Is it possible to make is so that an enchanted shulker box would work when inside your enchanted ender chest? For example let's say I have a shulker with food enchanted with refill. I would love to be able to put that shulker with food inside my enchanted ender chest and keep one stack of food in my hotbar. Then when I eat some food, it gets pulled from the shulker box that is inside the ender chest. 

I am really new to Java but thought it would be fun to try and see if I could mess with some things and add this functionality myself, so I tried looking at the code to see if maybe I could easily do it myself, but I really don't understand it much. (If you have a few pointers on where I could start if you think this is an easy change, that would really help me to try to do it myself.)

We love using this mod on our smp, and adding this functionality (maybe as a new option) would be really convenient for us as the players on our server use all the inventory space they can get, so anything we can put in an ender chest to free up an extra slot is really nice to have. Thank you!

**Comment by RubixDev** [comment]
The new option `nestedContainers` will be available in the upcoming 1.1.2 release and will be enabled by default. With it, it is even possible to have a shulker box inside an ender chest inside a shulker box in your inventory.
