### ISSUE TITLE
Minecraft 1.20?

### ISSUE THREAD

**Issue by luis-c465** [RubixDev/EnchantedShulkers#18]
Any update on when this mod will be compatible with Minecraft version `1.20`?

**Comment by RubixDev** [comment]
Uhm yes sorry, I was pretty busy the past week, I may find time to do this in the coming days

**Comment by ILikeFood971** [comment]
I worked on it and got a 1.20.1 version. It should probably work on 1.20 but I haven't tested it yet. You can [download it from here](https://github.com/ILikeFood971/EnchantedShulkers/releases/tag/v1.1.3) before the author publishes an official release. I pr in #19 so the author can probably just review that and release a new version soon.
