### ISSUE TITLE
Incompatible with Quick Shulker

### ISSUE THREAD

**Issue by DocAndrei** [RubixDev/EnchantedShulkers#20]
First drop an item onto the ground from hotbar with q then in inventory with an enchanted shulker box open (quick shulker mod) if I shift right click items from the hotbar into the shulker sometimes they dupe going into the shulker and a new stack appears in hotbar.

**Comment by RubixDev** [comment]
I got it fixed and EnchantedShulkers now works flawlessly in conjunction with QuickShulker :tada:
