### ISSUE TITLE
[Request] Vacuum enchantment

### ISSUE THREAD

**Issue by chimericdream** [RubixDev/EnchantedShulkers#22]
This would basically be like the siphon enchant, except it would be unfiltered. Everything coming into your inventory would try to go into the shulker box, as long as there is space.

**Comment by RubixDev** [comment]
The idea is interesting, but I'm not sure it would really be all that useful. I believe it would actually become rather annoying quite quickly that _everything_ you pick up is sucked into a shulker box. But I guess I might as well try to add it and have it be opt-in for users or something

**Comment by chimericdream** [comment]
Yeah. I was originally planning to request a config to toggle the behavior of siphon between "pick up everything" and "filtered pickup", but I had the same realization as you: not all players will want that behavior. As such, I figured that a separate enchantment would be the way to go, so players have to deliberately choose between the two (I think they would be mutually exclusive).
