### ISSUE TITLE
[Request] Different Siphon method

### ISSUE THREAD

**Issue by Nitjsefnie** [RubixDev/EnchantedShulkers#31]
This could be a level 2 Siphon or toggleable config, for some purposes it would be useful if it not only added to existing stacks, but created new stacks in case the existing stack is full.

**Comment by RubixDev** [comment]
Oh sorry, yea that sounds like a good idea to have as a config option to alter the behaviour of siphon

**Comment by RubixDev** [comment]
If you want to implement this yourself, I would add two config options to make Siphon or Vacuum behave like that. This way it is up to the user to just replace the Siphon functionality or to enable the Vacuum enchantment and override one of the enchantments with the new functionality. I don't think making this a level 2 would make sense and adding a new enchantment also seems a bit overkill.

I'd call the config options sth like `siphonFillNewSlots` and `vacuumRequireItemPresent` (I'm open to better names, they're not great) and make it clear in the descriptions that they both result in the same behaviour which is diffierent from any of the other enchantments.

In case you don't want to do the implementation, lmk and I will (eventually) do it myself.
