### ISSUE TITLE
Dupe glitch with Click Opener Mod

### ISSUE THREAD

**Issue by Guerdi** [RubixDev/EnchantedShulkers#36]
**Describe the bug**

**Platform(s)**

- [x] Quilt/Fabric

**Environment(s)**

- [ ] Singleplayer
and
- [x] Server

**Versions**
* Server Fabric 0.15.2
* Minecraft 1.20.1
* EnchantedShulkers 1.2.2
* ClickOpener 3.0.2

**To Reproduce**
1. Launch server
2. Run : 
             * /clear
             * /clickopener add blocktag minecraft:shulker_boxes
             * /clickopener reload
             * /gamemode survival
             * /give @s minecraft:shulkerbox

3. Hold the Shulker Box in your hand
4. Run :  
             * /enchant @s enchantedshulkers:siphon
             * /enchant @s enchantedshulkers:refill
             * /give @s minecraft:stone 64

6. Hold the Stone in your hand
7. Open your inventory and right click on the Shulker Box to open it
8. Drop some item in the Shulker Box (for example right click to divide the stack in 2 and place 32)
9. Once the Stone is in the Shulker Box, shit + left click on the stack in your hand to place it in the Shulker Box
10. Notice the dupe

**Comment by RubixDev** [comment]
Same issue as I had with QuickShulker and Shulker Box Slot previously; fixed in v1.2.3 :tada:
