### ISSUE TITLE
[Request]: Enlarge Enchantement

### ISSUE THREAD

**Issue by Guerdi** [RubixDev/EnchantedShulkers#37]
Just like the [Super Shulkers mod](https://modrinth.com/mod/super-shulkers) based on the very similar [Better Shulkers mod](https://github.com/arxenix/better-shulkers), there could be 3 levels of enchantment which would add a bar of 9 inventory slots, at the third level, the size of the Shulker Box is like a Double Chest.

It would also be interesting to make the size of the Ender Chest dependent on the enchantment level of the Ender Chest used, without enchantment the Ender Chest has the default size, with the third level it reaches full size as a double chest too.

I think the whole thing could be implemented server side without breaking anything and that would be a good balanced addition.

**Comment by RubixDev** [comment]
I've thought about this before, but so far always decided against it. I'm personally not really a fan of enlarging Shulker Boxes, I think the current enchantments provide a balanced vanilla-like way to more easily interact with Shulker Box contents, and there are other mods like Reinforced Shulkers that provide that sort of functionality and are compatible with EnchantedShulkers. However, I will leave this issue open for now and reconsider.

**Comment by RubixDev** [comment]
v1.2.4 has just been released and includes a new Augment enchantment which does exactly what you requested, just not for ender chests.
