### ISSUE TITLE
Incompatible with Peek

### ISSUE THREAD

**Issue by allanonmage** [RubixDev/EnchantedShulkers#42]
I see that you've added a description about resource packs, and [made a web page](https://enchantedshulkers.rubixdev.de/) to generate a custom mod with a custom resource pack.  But I think I'm still missing something.

Does this work with [henklemax ](https://modrinth.com/mod/peek)and [Iskall](https://modrinth.com/mod/shulker+)'s mods?  Or are you solving a different issue?

Since we're on the topic, is your mod compatible with those mods?  I'd like the automatic item on the outside feature that they offer, though I think I'm leaning towards henklemax's implementation since it's a set-it-and-forget-it kind of thing.

**Comment by RubixDev** [comment]
That description and web page are for users that use custom resource packs which change the look of shulker boxes. For _reasons_ EnchantedShulkers requires separate texture files with the same textures, just rearranged, and what that web page does is reading a resource pack and creating and adding those required files using the pack's existing shulker textures. It does **not** generate a mod and it has nothing to do with mod compatibility.

---

I have tested compatibility with Shulker+, but I was unaware of Peek until now. You can simply test that yourself in a creative world though and let me know whether it's working.

**Comment by RubixDev** [comment]
EnchantedShulkers wasn't actually really incompatible with Peek, just the yet to be released Augment enchantment didn't play well with the Peek shulker tooltips, but that has now also been fixed.
