### ISSUE TITLE
[FEATURE REQUEST] Allow Shulker boxes with refill enchantments to refill arrows inside inventory. 

### ISSUE THREAD

**Issue by RashidFTW** [RubixDev/EnchantedShulkers#43]
Lets say you have a shulker box with arrows inside, and it's enchanted with the refill enchantment.
Currently the arrows only refill if they are in your offhand. However, it's not really common practice to hold them there, usually they are either in your hotbar or your inventory. I would like the refill enchantment to refill arrows as they deplete when I shoot with a bow. 

I believe this exception should be made because bows/crossbows are the only items (that I can think of) that deplete something other than themselves (unlike blocks, items, ender pearls, food, snowballs, buckets, etc..). Currently the refill enchantment technically doesn't have any effect on the bow.

**Comment by RubixDev** [comment]
That's a great idea! The same goes for firework rockets which can also be shot by crossbows.

**Comment by RashidFTW** [comment]
I am impressed by how quick this got implemented! At first, was going to wait until the next mod version release, but was too thrilled to try it, so I did in the latest dev build. Works great and functions as expected, Love It!. Thanks again for your great work on this mod :D
