### ISSUE TITLE
Command for creating Enchanted Books?

### ISSUE THREAD

**Issue by akasnowmaaan** [RubixDev/EnchantedShulkers#5]
Maybe not an issue, but more of a question. 

What is the command for creating an Enchanted Book for these?
I wanted to test them out in my world before looking for them in treasure or via Piglin bartering (if they're offered there).

/give @p enchanted_book{Enchantments:[{id:siphon,lvl:1}]} 1
/give @p enchanted_book{Enchantments:[{id:refill,lvl:1}]} 1

I tried these two, and the books didn't work. No enchantments were added.
So, a few questions:

Are these enchantments enabled via the command line?
- If not, maybe that's a bug I'm reporting.
- If so, what am I getting wrong about the names?

TIA

**Comment by RubixDev** [comment]
> /give @p enchanted_book{Enchantments:[{id:siphon,lvl:1}]} 1
/give @p enchanted_book{Enchantments:[{id:refill,lvl:1}]} 1

Assuming the rest of the commands is correct, just changing `id:siphon` and `id:refill` to `id:"enchantedshulker:shiphon"` and `id:"enchantedshulkers:refill"` should work. IDs without a namespace prefix imply the default namespace `minecraft:`, which these enchantments do not exist in.

---

> I wanted to test them out in my world before looking for them in treasure or via Piglin bartering (if they're offered there).

The enchanted books should be very similar to Mending and other treasure enchantments, that is they...
- ...don't appear in enchantment tables
- ...are rarer
- ...can be obtained by fishing, villager trading and certain loot chests

I believe Piglins do *not* trade them, but I am not 100% sure.

---

Also for getting the books in a test world with cheats enabled, I think it is easiest to open the creative inventory and search for them there.

**Comment by akasnowmaaan** [comment]
Sweet, thank you!

**Comment by allanonmage** [comment]
I think this should be a note or item on the mod's page or wiki somewhere.  Glad to know that it's been documented somewhere though, but non-dev users would never think to look on Github methinks.

**Comment by RubixDev** [comment]
It's not really anything specific to this mod, but sure I can do that. I'm currently working on backports to 1.17 and 1.16 and will update the README and mod pages afterwards.

**Comment by RubixDev** [comment]
not done with the backports, but added [a readme section](https://github.com/RubixDev/EnchantedShulkers#i-just-wanna-quickly-try-em-out)
