### ISSUE TITLE
Anytime will be coming the version for 1.21 or newer.

### ISSUE THREAD

**Issue by wilebaldo** [RubixDev/EnchantedShulkers#59]
I'm just waiting to know if anytime soon will be the version for the 1.21? this is the only mod I'm waiting for to update. If not I will lost all the shulkers I already have with the enchanted.

**Comment by RubixDev** [comment]
I'll just paste a message from my Discord here:

> yes I will, but it will probably still take some time. for the past few weeks i've been really busy with real life stuff like coming back to germany and now searching for an apartment, so I haven't had time to program recently. Apart from that, I still need to update both EnchantedShulkers and Inventorio to 1.20.5/1.20.6 and EnchantedShulkers has more priority for me there. And then for the 1.21 updates I will probably also start with Rug and CarpetGamerules again, as they are usually quicker and easier to update, and then move on to EnchantedShulkers and finally Inventorio. So I hope I'll get to it eventually, but it'll likely still take a while.

original message: https://discord.com/channels/1184774025185079397/1214512216980717619/1253435391638507711 sent on June 20.
