### ISSUE TITLE
Incompatibility with Cursery

### ISSUE THREAD

**Issue by artem-mateush** [RubixDev/EnchantedShulkers#7]
I'm getting mixin errors when running this mod (v 1.18.2-1.0.4) with [Cursery](https://www.curseforge.com/minecraft/mc-mods/cursery) v 1.18.2-3.0

`---- Minecraft Crash Report ---- // This doesn't make any sense! Time: 23/10/2022, 17:51 Description: Initializing game java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1890 failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) 	at net.minecraft.class_1772.method_7807(class_1772.java:54) 	at net.minecraft.class_1772.method_7808(class_1772.java:78) 	at net.minecraft.class_1772.method_7850(class_1772.java:88) 	at net.minecraft.class_310.method_1546(class_310.java:784) 	at net.minecraft.class_310.<init>(class_310.java:576) 	at net.minecraft.client.main.Main.main(Main.java:197) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) 	at java.base/java.lang.reflect.Method.invoke(Method.java:577) 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) 	... 20 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1890::method_8214(Ljava/util/Map;Lnet/minecraft/class_1799;)V has incompatible changes at opcode 107 in callback enchantedshulkers.mixins.json:EnchantmentHelperMixin from mod enchantedshulkers->@Inject::set(Ljava/util/Map;Lnet/minecraft/class_1799;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_2499;)V.  Expected: [Lnet/minecraft/class_2499;]     Found: [] Available: [] 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547) 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 23 more A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) 	at net.minecraft.class_1772.method_7807(class_1772.java:54) 	at net.minecraft.class_1772.method_7808(class_1772.java:78) 	at net.minecraft.class_1772.method_7850(class_1772.java:88) 	at net.minecraft.class_310.method_1546(class_310.java:784) 	at net.minecraft.class_310.<init>(class_310.java:576) Mixins in Stacktrace: 	net.minecraft.class_310: 		fudge.notenoughcrashes.fabric.mixins.client.CatchInitMInecraftClientMixin (notenoughcrashes.fabric.mixins.json) 		de.rubixdev.enchantedshulkers.mixin.client.MinecraftClientMixin (enchantedshulkers.mixins.json) 		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.mixins.json) 		net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.mixins.json) 		net.fabricmc.fabric.mixin.command.client.MinecraftClientMixin (fabric-command-api-v1.mixins.json) 		fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json) 		net.fabricmc.fabric.mixin.event.interaction.MixinMinecraftClient (fabric-events-interaction-v0.mixins.json) 		net.fabricmc.fabric.mixin.registry.sync.client.MixinMinecraftClient (fabric-registry-sync-v0.mixins.json) 		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.mixins.json) 		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)`

**Comment by RubixDev** [comment]
It seems to work fine for me using 1.19 and I do not plan to support old Minecraft versions for this long, so I am closing this issue. In case you happen to run into the same problem with 1.19, feel free to re-open this.
