### ISSUE TITLE
compatibility with "Shulker Box Slot" mod.

### ISSUE THREAD

**Issue by dani626** [RubixDev/EnchantedShulkers#8]
The mod uses the trinkets library.
https://www.curseforge.com/minecraft/mc-mods/shulker-box-slot-fabric

**Comment by RubixDev** [comment]
That mod currently doesn't seem to work with 1.19.3, so I will wait for them to update before working on compatibility

**Comment by RubixDev** [comment]
(finally) fixed in https://github.com/RubixDev/EnchantedShulkers/commit/c023ddaa0d18548ca97ab2d3c42f9f6fa077cbcd. Will be available in v1.2.0 :tada:
